name:  CI - Test microservizio

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: docker-repository

    steps:
      - name: Checkout codice
        uses: actions/checkout@v3

      - name: Installa docker-compose
        run: |
          sudo curl -L \
            "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64" \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
      - name: Avvia servizi con docker compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Attendi inizializzazione db
        run: sleep 10

      - name: inizializzazione il database
        run: docker-compose -f docker-compose.yml exec microservizio python init_db.py

      - name: Esegui test
        run: docker-compose -f docker-compose.yml exec microservizio pytest 

      - name: Cleanup finale
        run: docker-compose -f docker-compose.yml down -v

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker build
        run: docker build -t secrets.DOCKER_USERNAME/container-lezione:$GITHUB_SHA .

      - name: Docker push
        run: docker push secrets.DOCKER_USERNAME/container-lezione:$GITHUB_SHA .